### ISSUE TITLE
Bug: API requests to TruckersMP failing

### ISSUE THREAD

**Issue by beast8891** [SamNuttall/TruckersMP-Info-Bot#5]
Alfie is not working for last few days (self hosted also ;)  we use both xD ) am adding a attachment [attachment](https://cdn.discordapp.com/attachments/1163434235445645373/1166255352514355240/Screenshot_30.png?ex=6549d2f0&is=65375df0&hm=d3efd0171ee06d6c7b12496e561585c4449578f284826ef2f87b7776a10d1990&)

**Comment by SamNuttall** [comment]
Hi there, thanks for your report! It does seem like there is an issue like you say. I'll take a look into it as soon as possible :)

**Comment by SamNuttall** [comment]
The issue has now been resolved (on the unstable branch) and the failed API requests should now be fixed.
It was an issue in the upstream library that the bot uses called [Async-TruckersMP](https://github.com/SamNuttall/Async-TruckersMP). 

If you do have any further problems related to this, feel free to reopen the issue. Thank you once again for reporting this!
