### ISSUE TITLE
Bug: /player command giving "Something went wrong" error

### ISSUE THREAD

**Issue by BEAST255220** [SamNuttall/TruckersMP-Info-Bot#6]
/player is not working some API issues

![Screenshot 2024-02-17 234859](https://github.com/SamNuttall/TruckersMP-Info-Bot/assets/122628376/b69441cb-3ad2-4526-89b6-794ba0fd1b76)

**Comment by SamNuttall** [comment]
Thanks for reporting this to me!

The issue has now been resolved (on the unstable branch) and the /player command should now work as expected.
It seems that TruckersMP have updated their /player endpoint response slightly, causing the validation on the response to fail.

Please let me know if you have any problems using the command still. I'll close this issue in a few days if everything seems fine.

**Comment by BEAST255220** [comment]
thank you :) .....now its working
